#!/bin/bash
#title          :batterymonitor
#description    :Monitors the battery and alerts the user if the battery exceeds the thresholds
#author         :mrblue
#date           :20191228
#version        :1.0
#usage          :./batterymonitor
#bash_version   :4.4.20(1)-release
#============================================================================

battery_level=$(upower -i $(upower -e | grep '/battery') | grep --color=never -E percentage | xargs | cut -d ' ' -f2 | sed s/%//)

state=$(upower -i $(upower -e | grep '/battery') | grep --color=never -E state | xargs | cut -d ' ' -f2 | sed s/%//)

if [[ $state == 'charging' || $state == 'fully-charged' && $battery_level -gt 80 ]] 
then
export DISPLAY=:0.0 
zenity --warning --text "Battery is above 80%\n<b>Current Level: $battery_level%</b>\n\n<span foreground='red'>Please Disconnect the Charger.</span>" --title "Battery Alert" --no-wrap;
fi

if [[ $state == 'discharging' && $battery_level -lt 35 ]] 
then
export DISPLAY=:0.0
zenity --warning --text "Battery is Low\n<b>Current Level: $battery_level%</b>\n\n<span foreground='red'>Please Connect the Charger.</span>" --title "Battery Alert" --no-wrap;
fi
