#!/bin/bash
#title          :enablewifi
#description    :Enables Wifi in Linux mint 19
#author         :mrblue
#date           :20191228
#version        :1.0
#usage          :./enablewifi
#bash_version   :4.4.20(1)-release
#============================================================================

git clone -b extended https://github.com/lwfinger/rtlwifi_new.git
sudo dkms add ./rtlwifi_new
sudo dkms install rtlwifi-new/0.6
sudo modprobe -r rtl8723de && sudo modprobe rtl8723de
echo "options rtl8723de ant_sel=2" | sudo tee /etc/modprobe.d/rtl8723de.conf
