#!/bin/bash
#title          :notify
#description    :Notifies the user with an audio
#author         :mrblue
#date           :20191228
#version        :1.0
#usage          :./notify
#bash_version   :4.4.20(1)-release
#============================================================================

#amixer -q -D pulse set Master 80%
paplay /usr/share/sounds/freedesktop/stereo/complete.oga
notify-send $1