#!/bin/bash     
#title          :wpdownload
#description    :Downloads Wallpaper from reddit link
#author         :mrblue 
#date           :20200117
#version        :1.0    
#usage          :./wpdownload
#bash_version   :4.4.20(1)-release
#============================================================================        

# Reddit Address
REDDIT="http://www.reddit.com/r/Animewallpaper/new/"

# Download location
# For example: /home/user/Pictures
LOC="/mnt/Storage/Pictures/Wallpapers/"

read -p "test"

# Download stuff from Reddit Address
for x in `wget -O - $REDDIT | grep -Eo 'http://[^&]+(jpg|png)' | grep -v "\"" | awk '{print $1}' | tail -n +3 | uniq`
do
	# As long as the wallpaper doesn't already exist
	if [[ ! -f "$LOC/${x##*/}" ]]; then

		# Get those wallpapers and put them in a folder!
		wget -P "$LOC" $x

		# Determine aspect rastio of file
		RATIO=`identify -format "%[fx:w/h]" "$LOC/${x##*/}"`

		# Check if the wallpaper is 16:9
		if [[ $(echo "$RATIO < 2" | bc) -eq 1 ]] && [[ $(echo "$RATIO >= 1" | bc) -eq 1 ]]; then

			# Delete the image
			rm "$LOC/${x##*/}" -rf

			# Alert user
			echo "Image was not 16:9. Deleted!"

		else

			# Alert user
			echo "Image is 16:9!"
		fi

	fi
done

# Get rid of images that are not 16:9 or HD
while read line
do

	# Determine aspect ratio and width of the file
	RATIO=`identify -format "%[fx:w/h] %w" "$LOC/$line"`
	RWIDTH=`echo $RATIO | awk '{print $2}'`
	RATIO=`echo $RATIO | awk '{print $1}'`

	    # Check if the wallpaper is 16:9
        if [[ $(echo "$RATIO < 2" | bc) -eq 1 ]] && [[ $(echo "$RATIO >= 1" | bc) -eq 1 ]]; then

		# Check file and determine if it matches the criteria
		if [[ $RWIDTH -lt "1280" ]]; then

			# Alert user to discrepency
			echo "Deleting $line. It's in 16:9, but it's not HD!"

			# Remove file
			rm -rf "$LOC/$line"

		else

			# Alert user of satisfying parameters (lol)
			echo "Keeping $line"
		fi
	else

		# Alert user to discrpency
		echo "Deleting $line. It's not even in 16:9! Instead, its ratio is $RATIO."

		# Remove file
              rm -rf "$LOC/$line"
	fi

# This was a pain in the neck to write
done <<< "`cd \"$LOC\" && dir -DR *`"


